services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: mohamed
      POSTGRES_PASSWORD: 1234
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - postgres
    restart: unless-stopped

  customer-service:
    build:
      context: ./customer
      dockerfile: Dockerfile
    container_name: customer-service
    ports:
      - "8081:8080"
    networks:
      - spring
    depends_on:
      - postgres

  bank-account-service:
    build:
      context: ./bankaccount
      dockerfile: Dockerfile
    container_name: bank-account-service
    ports:
      - "8082:8080"
    networks:
      - spring
    depends_on:
      - postgres

  transaction-service:
    build:
      context: ./transaction
      dockerfile: Dockerfile
    container_name: transaction-service
    ports:
      - "8083:8080"
    networks:
      - spring
    depends_on:
      - postgres

  loan-service:
    build:
      context: ./loan
      dockerfile: Dockerfile
    container_name: loan-service
    ports:
      - "8084:8080"
    networks:
      - spring
    depends_on:
      - postgres

  card-service:
    build:
      context: ./card
      dockerfile: Dockerfile
    container_name: card-service
    ports:
      - "8085:8080"
    networks:
      - spring
    depends_on:
      - postgres

  # Uncomment when needed:
  # zipkin:
  #   image: openzipkin/zipkin
  #   container_name: zipkin
  #   ports:
  #     - "9411:9411"
  #   networks:
  #     - spring
  # rabbitmq:
  #   image: rabbitmq:3.9.11-management-alpine
  #   container_name: rabbitmq
  #   ports:
  #     - "5672:5672"
  #     - "15672:15672"
  #   networks:
  #     - spring

networks:
  postgres:
    driver: bridge
  spring:
    driver: bridge

volumes:
  postgres:
  pgadmin:
