services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: mohamed
      POSTGRES_PASSWORD: 1234
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - postgres
    restart: unless-stopped

  

  customer:
    build:
      context: ./customer
      dockerfile: Dockerfile
    container_name: customer-service
    ports:
      - "8081:8080"
    networks:
      - spring
    depends_on:
      - postgres

  bankaccount:
    build:
      context: ./bankaccount
      dockerfile: Dockerfile
    container_name: bank-account-service
    ports:
      - "8082:8080"
    networks:
      - spring
    depends_on:
      - postgres

  transaction:
    build:
      context: ./transaction
      dockerfile: Dockerfile
    container_name: transaction-service
    ports:
      - "8083:8080"
    networks:
      - spring
    depends_on:
      - postgres

  card:
    build:
      context: ./card
      dockerfile: Dockerfile
    container_name: card-service
    ports:
      - "8085:8080"
    networks:
      - spring
    depends_on:
      - postgres


networks:
  postgres:
    driver: bridge
  spring:
    driver: bridge

volumes:
  postgres:
  pgadmin:
