version: '3.8'

services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: mohamed
      POSTGRES_PASSWORD: 1234
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - spring
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - spring
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - spring

  # Customer microservice
  customer:
    build:
      context: ./customer
      dockerfile: Dockerfile
    container_name: customer-service
    ports:
      - "8081:8080"
    networks:
      - spring
    depends_on:
      - postgres

  # Bank Account microservice
  bankaccount:
    build:
      context: ./bankaccount
      dockerfile: Dockerfile
    container_name: bank-account-service
    ports:
      - "8082:8080"
    networks:
      - spring
    depends_on:
      - postgres

  # Transaction microservice
  transaction:
    build:
      context: ./transaction
      dockerfile: Dockerfile
    container_name: transaction-service
    ports:
      - "8083:8080"
    networks:
      - spring
    depends_on:
      - postgres

  # Card microservice
  card:
    build:
      context: ./card
      dockerfile: Dockerfile
    container_name: card-service
    ports:
      - "8085:8080"
    networks:
      - spring
    depends_on:
      - postgres

  # Loan microservice
  loan:
    build:
      context: ./loan
      dockerfile: Dockerfile
    container_name: loan-service
    ports:
      - "8084:8080"
    networks:
      - spring
    depends_on:
      - postgres

  # Notification microservice
  notification:
    build:
      context: ./notification
      dockerfile: Dockerfile
    container_name: notification-service
    ports:
      - "8086:8080"
    networks:
      - spring
    depends_on:
      - postgres

networks:
  spring:
    driver: bridge

volumes:
  postgres:
  pgadmin:
