server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # enables dynamic routing via Eureka

      routes:
        - id: customer
          uri: lb://customer
          predicates:
            - Path=/api/v1/customer/**

        - id: card
          uri: lb://card
          predicates:
            - Path=/api/v1/card/**

        - id: transaction
          uri: lb://transaction
          predicates:
            - Path=/api/v1/transaction/**

        - id: bankaccount
          uri: lb://bankaccount
          predicates:
            - Path=/api/v1/bankaccount/**

        - id: loan
          uri: lb://loan
          predicates:
            - Path=/api/v1/loan/**
springdoc:
  swagger-ui:
    urls:
      - name: Customer Service
        url: http://localhost:8081/v3/api-docs
      - name: Card Service
        url: http://localhost:8082/v3/api-docs
      - name: Transaction Service
        url: http://localhost:8083/v3/api-docs
      - name: BankAccount Service
        url: http://localhost:8084/v3/api-docs
      - name: Loan Service
        url: http://localhost:8085/v3/api-docs

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
