server:
  port: 8084
spring:
  application:
    name: loan
  datasource:
    password: 1234
    url: jdbc:postgresql://localhost:5432/loan
    username: mohamed
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
    enabled: true

account:
  service:
    url: http://localhost:8082/api/v1/bank-accounts

customer:
  service:
    url: http://localhost:8081/api/v1/customers
