server:
  port: 8082

spring:
  application:
    name: bankaccount
  datasource:
    password: 1234
    url: jdbc:postgresql://localhost:5432/bankaccount
    username: mohamed
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
    enabled: true

logging:
  level:
    root: OFF # Disable all logs globally
    org.springframework: ERROR # Only show errors from Spring
    org.hibernate: ERROR # Only show errors from Hibernate
    com.mohammedhany: DEBUG # Show all your logs from this package

customer:
  service:
    url: http://localhost:8080/api/v1/customers

notification:
  service:
    url: http://localhost:8086/api/v1/notifications
